### ISSUE TITLE
Resource suggestion: IntersectionObserver

### ISSUE THREAD

**Issue by LucaRosaldi** [Modernizr/modernizr-neue#119]
Given the growing popularity of the [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API), it would be cool to have a test to detect support, i.e.

```javascript
if ( 'IntersectionObserver' in window ) {
  // supports IntersectionObserver
}
```

**Comment by rejas** [comment]
Correct, but this is an issue for the main repo, could you file a request at https://github.com/Modernizr/Modernizr ?

**Comment by rejas** [comment]
Opened issue https://github.com/Modernizr/Modernizr/issues/2331, this can be closed @LucaRosaldi
