### ISSUE TITLE
GET https://modernizr.com/js/index.js 404 (Not Found)

### ISSUE THREAD

**Issue by paulirish** [Modernizr/modernizr-neue#13]
![image](https://cloud.githubusercontent.com/assets/39191/9829564/0eac97d2-58be-11e5-84ac-190c4041371a.png)

**Comment by patrickkettner** [comment]
something is screwy in the build step. this should be [the fontface-observer](https://github.com/Modernizr/modernizr-neue/blob/0b313457a990ff32dd1bfc6eb0dbbe4186fa2a22/frontend/js/index.js)

**Comment by patrickkettner** [comment]
fixed by #20
