### ISSUE TITLE
Make new Builder track builds in GA again

### ISSUE THREAD

**Issue by KuraFire** [Modernizr/modernizr-neue#15]
We had this for the old builder:

```js
// Track the different builds
if ( window._gaq ) {
    _gaq.push(['_trackPageview', '/build/'+[].slice.call($('ul li input:checked').map(function(key, val){ return ($(this).closest('li')[0].id || undefined); }), 0).join("^")]);
}
```

We’ll have to adapt it to the new builder.

Current proposal:

1. Continue to track it as pageviews
1. Track based on user clicking the Build button (so that we don't have to implement anything highly custom to deal with the *7* download/copy/open in codepen options inside the Build modal)
1. Keep the same build URL structure for the Analytics; the date– and time-stamp allows us to filter out if we need to (but there isn't much value to it at this time)

**Comment by ryanseddon** [comment]
Closed via #23
