### ISSUE TITLE
ServiceWorker is throwing an error

### ISSUE THREAD

**Issue by ryanseddon** [Modernizr/modernizr-neue#26]
So the service worker isn't actually installing, it throws trying to [import a script](https://github.com/Modernizr/modernizr-neue/blob/master/frontend/js/download/workers/serviceworker.js#L2) that doesn't exist.

@patrickkettner where does this script come from?

**Comment by patrickkettner** [comment]
Bower

**Comment by patrickkettner** [comment]
fixed as of 284430
