### ISSUE TITLE
Hapi caching in develop mode

### ISSUE THREAD

**Issue by joecritch** [Modernizr/modernizr-neue#28]
Hey, I'm running `npm run develop` and building some changes to `frontend/js/download/downloader.js`, but the version shown through `http://localhost:3000/js/download/downloader.js` seems to be heavily cached by Hapi, so my changes aren't appearing on the local server.

Has anyone else encountered this?

cc @patrickkettner

**Comment by patrickkettner** [comment]
Are you sure it isn't the service worker doing the caching?

**Comment by joecritch** [comment]
Oh, possibly. I'm not sure what a service worker is though! :) Is there any way to disable it during development?

**Comment by patrickkettner** [comment]
You can check the settings in chrome://serviceworker-internals. But the
simplest thing is just run it in an incognito window

**Comment by joecritch** [comment]
I think it spawns a new service worker when hapi restarts, so can't disable it. But yeah, this seems to be the cause. `Cmd+Shift+R` to the rescue.

Thanks dude.

**Comment by joecritch** [comment]
Just a thought, does the service worker also cache the JS on the server? We probably need a way to bust it to push new releases through.

**Comment by patrickkettner** [comment]
No. It's client side
