### ISSUE TITLE
Custom build still has alpha in version and old URL

### ISSUE THREAD

**Issue by KuraFire** [Modernizr/modernizr-neue#31]
This is the comment at the top of a customized build:

```
/*! modernizr 3.0.0-alpha.4 (Custom Build) | MIT *
 * http://modernizr.com/download/#-batteryapi-blobconstructor-canvas !*/
```

There are 4 tiny issues:

1. Modernizr not capitalized
1. release version is not `-alpha.4` anymore
1. **https** now, not http
1. `#-` after `/download/` should just read `?` (e.g. `/download/?batteryapi-blob…`)

**Comment by patrickkettner** [comment]
this was an issue with the server side config. it has been fixed for a while now
