### ISSUE TITLE
Renamed browser features get removed from custom build url

### ISSUE THREAD

**Issue by judowalker** [Modernizr/modernizr-neue#33]
I have a custom build of Modernizr version 2.8.3. When I copy/paste the custom build url into the browser, some of the browser features get removed from the url.

For example:
http://modernizr.com/download/#-rgba-cssanimations-input-shiv-cssclasses-testprop-testallprops-domprefixes-file_api

The file_api browser feature is removed from the url. I just happened to notice this. If I didn't, I would have downloaded a new build which would be missing the file_api feature.

It looks like the feature changed from file_api to filereader. Perhaps you can have some sort of mapping for features whose names have changed and update the url.

**Comment by ryanseddon** [comment]
Thanks for the reporting @judowalker that's now fixed. See #46.

**Comment by judowalker** [comment]
Thanks for fixing.
