### ISSUE TITLE
`touch` renamed to `touchevents` is a breaking change

### ISSUE THREAD

**Issue by bravokiloecho** [Modernizr/modernizr-neue#34]
This was mentioned on twitter (see screengrab at bottom).

True, you can rename the test is JS like:

```
 Modernizr. Touch = Modernizr.touchEvents
```
but this is not ideal. I also use the `html.touch` in my CSS quite often so I'll have to go through all of that and change it too.

So now when you want to add a new Modernizr test to an old project, you'll have to modify the project's other JS and CSS files too. This seems like a strong argument against a breaking change in v3. Is there a good reason for renaming the test?

![image](https://cloud.githubusercontent.com/assets/5556900/9903147/c1e4ca8a-5c6b-11e5-9ab9-466b380b6166.png)

**Comment by SlexAxton** [comment]
It's also mentioned in the changelog for v3. We waited until a major version change to make this change, so I feel pretty comfortable, but this was a huge source of confusion in the last version.

The long answer is tucked away in some older issues we can dig up, but the short answer is that people used the `touch` detect to determine whether the user was using a touch device or a mouse. This is in no way what the detect implies, though. It only implied that touch events were supported on that device (and only one type of touch events at that). There are plenty of devices (chrome books for instance) that pass the old `touch` test, but we're primarily mouse machines.

I'm fine with some blessed third party code that duplicates the class or something for legacy users, but I still fully agree with the decision to change the names to the real detect intents here.

**Comment by bravokiloecho** [comment]
Thanks for your thoughts @SlexAxton, they definitely make sense and I respect that with such a major overhaul, these kind of changes are justifiable.

I wonder then if it might be a nice service to host the v2 website and builder somewhere (with a link from the new site). This would meant that if we're modifying the Modernizr build for preexisting projects we can go there and not have to worry about modifying the rest of the code.

This needn't be done indefinitely of course, but just to cover some kind of transition period.

**Comment by patrickkettner** [comment]
Out of curiosity, if you don't want to update your code, why do you want to
regenerate Modernizr?

**Comment by bravokiloecho** [comment]
Sometimes you want to add new features without breaking code that previously worked fine...

In this particular instance, I wanted to add a test for CSS pointer events and run a function depending on the result. But when adding an encapsulated piece of functionality I would rather not have to modify other parts of the JS _as well as_ the sitewide CSS.

Imagine you come back to an old project that uses Modernizr (maybe it wasn't even yours in the first place). You want to add a new functionality that would involve adding a new feature detect. So you head over to modernizr.com, build a new version and add it to your project. Suddenly a lot of things start breaking and it's not obvious why. You will eventually figure it out (maybe you'll even read the changelogs) and you will eventually resolve the issues, but not before experiencing stress and expending unexpected effort.

Modernizr is a great tool and I'm really pleased and grateful so many talented people have generously given up their time to making other developers' jobs easier. My thoughts, I hope, are in the spirit of this goal.

**Comment by patrickkettner** [comment]
I 100% empathize with the sentiment, but a simple find a replace in your project will take care of all of this. Sublime, Atom, TextWrangler, Vim, Emacs... any real text editor editor really, can update this for you in less time than it takes me to write this sentence, let alone make a new build of Modernizr.

If you _really_ ___need___ to build a v2 version, fork [the old .com](https://github.com/modernizr/modernizr.com) and use it's gh-pages.
