### ISSUE TITLE
Footer on builder page obscures side panel

### ISSUE THREAD

**Issue by bravokiloecho** [Modernizr/modernizr-neue#35]
When you scroll to the bottom on the builder page, the footer obscures the bottom of the side panel. See image below:

![image](https://cloud.githubusercontent.com/assets/5556900/9903266/0784d174-5c6d-11e5-86ad-c4813c6756c4.png)

**Comment by patrickkettner** [comment]
@bravokiloecho it should scroll - does it?

**Comment by bravokiloecho** [comment]
You mean the side panel?
If so, yes it does, but not enough to make all of its content visible.

**Comment by patrickkettner** [comment]
@joecritch what do you think should happen here?

**Comment by joecritch** [comment]
@patrickkettner See #43 as a suggestion. Ideally, we'd probably shift the entire UI up to accommodate for a full-width footer, but that's probably more work than the value it'd bring.

**Comment by bravokiloecho** [comment]
I like your footer restyling suggestion @joecritch. I wonder if that is implemented then it makes sense to have the options column extend the full height of the screen. I've made some edits in the commit 5f4fe451ce9026638ecfb0e1ea6e4425631f7ffc which looks like this:

![image](https://cloud.githubusercontent.com/assets/5556900/9989179/41432fca-604e-11e5-9b17-67c75d19e2d1.png)

**Comment by joecritch** [comment]
@bravokiloecho Hey, curious how you managed to create that commit? Which branch is it on? (I'd just like to review locally and potentially merge into my PR)

**Comment by paulirish** [comment]
it's over on his fork. 
https://github.com/Modernizr/modernizr-neue/compare/master...bravokiloecho:master

(github will honor any hash, which is kinda confusing)

**Comment by patrickkettner** [comment]
@joecritch did you get a chance to review @bravokiloecho's change?

**Comment by joecritch** [comment]
@patrickkettner Looks great, thanks @bravokiloecho. I've updated #43 accordingly.
