### ISSUE TITLE
Responsive nav funkiness in Safari

### ISSUE THREAD

**Issue by vasuvasu** [Modernizr/modernizr-neue#36]
Was looking at the new site (looks great!) and noticed I was getting scroll bars when at a smaller window size. Attached is a screenshot of how it looks in Safari 8 and 9 (in the El Capitan GM). Looks fine in IE10+, Edge, Chrome, Firefox. Didn't dig in too much into what's causing it, but any thoughts now what's going on here? Looks flex-wrap related? 
![screen shot 2015-09-16 at 10 44 04 am](https://cloud.githubusercontent.com/assets/2042056/9910353/5bcef512-5c62-11e5-9a2c-e0f4463c08cc.png)

**Comment by patrickkettner** [comment]
The issue is that flex-wrap isn't working correctly (the last two menu items are missing).

I remember there being a thing with min-width and flex-wrap with safari, but I haven't messed with it lately. 

@ryanseddon @joecritch if you had a minute to mess with this

**Comment by ryanseddon** [comment]
Found it https://github.com/philipwalton/flexbugs#11-min-and-max-size-declarations-are-ignored-when-wrapping-flex-items thank you @philipwalton

@vasuvasu wanna do a PR to fix this?

**Comment by patrickkettner** [comment]
ping @vasuvasu
