### ISSUE TITLE
Custom Builder Check Issues

### ISSUE THREAD

**Issue by Dangoo** [Modernizr/modernizr-neue#37]
https://modernizr.com/download

Case: An item is selected and I want to deselect it.
Problem: On first click item doesn't get inactive, first on second click.

![modernizr_](https://cloud.githubusercontent.com/assets/1252204/9910640/5f6a7b1a-5c9e-11e5-995c-0859dbc4d0f7.gif)

**Comment by patrickkettner** [comment]
Thanks for he report! This is actually a rendering issue. The data is
getting out of sync, if you expand an item it will rerender. I'll get this
fixed asap

**Comment by patrickkettner** [comment]
fixed in 8162cb3fc4aafc58d0d6f46491b6a0724d563be3
