### ISSUE TITLE
Check marks render badly in Firefox

### ISSUE THREAD

**Issue by bighuggies** [Modernizr/modernizr-neue#39]
When I select a feature in Firefox the tick is misaligned within the circle:

![modernizr_marks](https://cloud.githubusercontent.com/assets/597021/9922714/dc067c40-5d3f-11e5-944b-d3970f772d75.png)

This is in Firefox Developer Edition 42.0a2 (2015-09-14) on Windows 8.1

**Comment by patrickkettner** [comment]
thanks for the report! #44 seems to be taking care of this, so I am going to close this out in favor of it.
