### ISSUE TITLE
Toggle icon don't render properly in some browsers

### ISSUE THREAD

**Issue by tomsarduy** [Modernizr/modernizr-neue#44]
Seems like the checked toggle state SVG icon is not rendered properly in Safari, at least in Version 8.0 (10600.1.25)
![screen shot 2015-09-22 at 2 22 59 pm](https://cloud.githubusercontent.com/assets/1388092/10027570/c4ec6a5c-6135-11e5-8d26-304e0cd76415.png)

**Comment by ryanseddon** [comment]
Noticed this on iPhone too. Wanna try and put a pr together?

**Comment by tomsarduy** [comment]
@ryanseddon yeap, let's try... also, this is how it looks in Firefox 40, it's weird that modernizr website don't use Modernizr to test ;)
![screen shot 2015-09-22 at 3 55 06 pm](https://cloud.githubusercontent.com/assets/1388092/10029846/547a9fe8-6142-11e5-9565-6dbdea6aa4ea.png)

**Comment by patrickkettner** [comment]
yes it does.​ we just don't have a way to detect svg element css transforms
(yet)

**Comment by tomsarduy** [comment]
@patrickkettner, as you mentioned, the issue have to do with applying css transforms to SVG elements in some cases. There is a [great post in CSS Tricks](https://css-tricks.com/svg-animation-on-css-transforms/) about this subject. There are some well known issues, but specifically I found an issue with css transform rotate and svg attribute `stroke-dashoffset`, seems like safari don't calculate it right. Most people recommend doing the animations using [GreenSock JS](https://github.com/greensock/GreenSock-JS) (faster than jQuery animations).

@ryanseddon: I made a [Pen](http://codepen.io/tomsarduy/pen/BoLRjp) for the toggle using div and css3 animations and at least is working in Firefox, Safari and of course Chrome, but I don't know how to merge it with ReactJS (yet)

**Comment by patrickkettner** [comment]
@tomsarduy great work!

youll want to modify (SVGToggle)[https://github.com/Modernizr/modernizr-neue/blob/master/frontend/js/download/SVGToggle.js] (probably renaming the file and its references), and its related [styles](https://github.com/Modernizr/modernizr-neue/blob/master/frontend/styl/builder/toggle.styl)

**Comment by stof** [comment]
this also affect Firefox 51
![modernizer_bug](https://cloud.githubusercontent.com/assets/439401/23413394/d6c5ba9e-fdd8-11e6-8215-4f0f58c08fd4.png)

**Comment by toptalo** [comment]
I think I fix this in PR #110. But Travis CI fails. So I fix it too in PR #111

**Comment by toptalo** [comment]
Up!

**Comment by patrickkettner** [comment]
sorry, this was already published

**Comment by toptalo** [comment]
@patrickkettner Hello! Toggle Icons on https://modernizr.com/download are still broken
