### ISSUE TITLE
Search Function Broken

### ISSUE THREAD

**Issue by prestonmcp** [Modernizr/modernizr-neue#63]
It looks like the searching and creating a build is funky (sorry can't be more descriptive). 
If I type 'bo' then 'box shadow' shows up, but as soon as I type 'box' it disappears :( 
![image](https://cloud.githubusercontent.com/assets/7770587/10754182/4409e8fe-7c53-11e5-8c14-2237988b5c75.png)
![image](https://cloud.githubusercontent.com/assets/7770587/10754186/4b62fbae-7c53-11e5-8200-d344c75978ac.png)

**Comment by patrickkettner** [comment]
Hey Preston!
hm...I am not able to replicate this. Can you give more information as to
what browser you are using?

**Comment by prestonmcp** [comment]
I'm using Chrome :cry:

**Comment by patrickkettner** [comment]
strange - I am too. Can you screen cap searching for "bo" and "box"?

On Tue, Oct 27, 2015 at 1:46 PM, Preston <notifications@github.com> wrote:

> I'm using Chrome [image: :cry:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Modernizr/modernizr-neue/issues/63#issuecomment-151638612>
> .
>



-- 
patrick

**Comment by prestonmcp** [comment]
I did in the first post, are they not visible?

**Comment by patrickkettner** [comment]
oh, im sorry. I was checking them via email and they weren't there. sorry!

This is what I am seeing
![image](https://cloud.githubusercontent.com/assets/465414/10772338/dacc2d60-7cb2-11e5-8a85-9f36d8522e2c.png)

could you screencap the entire browser window? I am confused as to what is going on. 

Would you happen to have configured a language other than en-us in your browser?

**Comment by prestonmcp** [comment]
Wow I'm not sure why, I just tried again and it works. Hmm. Anyways, thanks for checking!
~

**Comment by patrickkettner** [comment]
![image](https://cloud.githubusercontent.com/assets/465414/10772976/09cd5e4c-7cb6-11e5-8e90-857b0ab63682.png)


cheers!
