### ISSUE TITLE
Resource suggestion: CDN - always LATEST version  

### ISSUE THREAD

**Issue by mleathem** [Modernizr/modernizr-neue#64]
suggested CDN arent even v3:

- http://cdnjs.com/libraries/modernizr
- http://www.asp.net/ajax/cdn

Thanks & Keep up the good work

**Comment by patrickkettner** [comment]
Hi @mleathem!
We don't control those CDNs, and in addition, there is no longer any kind of single file representing Modernizr as there was in the past. You'll want a custom build representing only the detects _your_ site needs

cheers!
