### ISSUE TITLE
CSS class prefix does not apply from build url

### ISSUE THREAD

**Issue by jstewsy** [Modernizr/modernizr-neue#79]
Doesn't seem like the `css class prefix` is being set when coming from a build url

example: 

```
http://modernizr.com/download?-cssanimations-csstransitions-touchevents-domprefixes-mq-prefixed-prefixes-setclasses-testallprops-testprop-teststyles-dontmin-cssclassprefix:modernizr-
```

**What is expected::**

_modernizr build page with all customizations checked and input areas filled out_

**What happens::**
_all customizations including  add class are checked to be used; however, the field for class prefix isn't populated with the passed in url attribute. In this example I would expect to see -_

```
(✓) Add CSS classes
...with prefix [ modernizr- ]
```

**Comment by ryanseddon** [comment]
Thanks for the bug report, if you want to have a go at putting a PR together to fix this I'd start by looking at [index.js](https://github.com/Modernizr/modernizr-neue/blob/master/frontend/js/download/index.js#L49) and see what that is doing with the `cssclassprefix:modernizr-` syntax.

**Comment by jstew529** [comment]
@ryanseddon checkout https://github.com/Modernizr/modernizr-neue/issues/72#issuecomment-188465937

**Comment by examinedliving** [comment]
I second this issue.
