### ISSUE TITLE
Resource suggestion: updated tutorials

### ISSUE THREAD

**Issue by dnahodil** [Modernizr/modernizr-neue#84]
The tutorials listed on the website (https://modernizr.com/resources) are between 4 and 7(!) years old. As someone about to get started for the first time with Modernizr 3 these are completely irrelevant.

Cheers,

**Comment by patrickkettner** [comment]
do you have any recomendations?

On Thu, Jun 16, 2016 at 1:01 AM, David Nahodil <notifications@github.com>
wrote:

> The tutorials listed on the website (https://modernizr.com/resources) are
> between 4 and 7(!) years old. As someone about to get started for the first
> time with Modernizr 3 these are completely irrelevant.
>
> Cheers,
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Modernizr/modernizr-neue/issues/84>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAcaBhSgmpenCgrrsojGpByaPqVQHUboks5qMNiQgaJpZM4I3BuI>
> .
>



-- 
patrick

**Comment by dnahodil** [comment]
I'm afraid I don't, Patrick. Like I said I'm only just getting started with Modernizr right now (like today 😄 ).

I was looking for tutorials for myself and started reading some of those before I noticed these were quite out of date.

I'm not trying to be unhelpful, but I genuinely don't know of any good resources, yet.

**Comment by patrickkettner** [comment]
oh, I don't think you are being unhelpful at all! I really appreciate you reporting it.

What resources were out of date?

**Comment by dnahodil** [comment]
Okay, good. I just said that because I know open source is about helping fix things not just saying "it is broken". :+1:

So the resources I'm talking about are the 5 links under the 'tutorials' heading.

**Comment by patrickkettner** [comment]
sorry, I meant in what way are they outdated?

**Comment by dnahodil** [comment]
Ah, I see. I can check  tomorrow (time for home, now).

Certainly URLs will be for old versions. But I guess the new way to build Modernizr won't be covered.

**Comment by patrickkettner** [comment]
Some screenshots wouldbe out of date, but overall all of the data _should_ be accurate (despite their age - the process for building hasn't changed outside of the color and location of the checkboxes and buttons).

**Comment by dnahodil** [comment]
It was my understanding (I now see that I was wrong) that the way to get Modernizr had changed a lot in version 3. So that had made me think that the tutorials which were written a while ago would be out of date with their instructions. That is not the case. 👍 

So, I've just gone through the 5 linked tutorials to see if any were actually giving out of date information. (I don't count the layout of the Modernizr page changing to be a problem.)

https://hacks.mozilla.org/2012/07/the-web-developer-toolbox-modernizr/ - This article seems to be fine

http://alistapart.com/article/taking-advantage-of-html5-and-css3-with-modernizr
http://webdesignernotebook.com/css/how-to-use-modernizr/
http://www.andismith.com/blog/2012/02/modernizr-prefixed/
These three suggest there is a standard version you can get just by going to the Modernizr download page without customising it. I'm not sure if that's true anymore, I think you still go through a build step with the development version. This *may* cause a little confusion but a lot of users will work it out.

https://www.sitepoint.com/premium/courses/modernizr-front-end-development-done-right-2561
There is a link at the top of this page which suggests a Modernizr 3 version of the course (https://www.sitepoint.com/premium/courses/a-beginners-guide-to-modernizr-3-2905). Perhaps the tutorial link on the Modernizr website should link straight there?

I thought these tutorials would be quite out of date but I now see that they aren't. So I'm happy for you to close this issue. With my findings from reading those articles a bite more carefully my only suggestion now is maybe to link to the Modernizr 3 version of Ryan Seddon's course.

Thanks for listening, Patrick 👍
