### ISSUE TITLE
Usage of comma-separated features is wrong

### ISSUE THREAD

**Issue by jessetan** [Modernizr/modernizr-neue#86]
The features `todataurljpeg`, `todataurlpng` and `todataurlwebp` are rendered as a single string on the website:
![modernizr-meta](https://cloud.githubusercontent.com/assets/3284111/16649841/282aea06-443b-11e6-8d29-765bc25f63ed.png)

In the example dialog, this also happens:
![modernizr-example](https://cloud.githubusercontent.com/assets/3284111/16649842/283d806c-443b-11e6-91db-188147ec0392.png)

A better example would be:

``` js
if (Modernizr.todataurljpeg) {
  // supported
} else if (Modernizr.todataurlpng) {
  // supported
} else if (Modernizr.todataurlwebp) { 
  // supported
} else {
  // not-supported
}
```

**Comment by rejas** [comment]
Happens with all feature tests that have an array as their property, for example 
```
  "property": ["devicemotion", "deviceorientation"],
```
in
deviceorientation-motion
